### ISSUE TITLE
Add support for 'on' event handlers

### ISSUE THREAD

**Issue by Bomper** [pladaria/html5-websocket#5]
If I use the WebSocket constructor for ReconnectingWebSocket, I can write

```js
rws.on('open', () => { ... });
```

After [switching to html5-websocket](https://github.com/pladaria/reconnecting-websocket/issues/48#issuecomment-357597059), the code using WebSocket no longer works, and I have to switch to `onopen` etc.

**Comment by pladaria** [comment]
Hi, thanks for your feedback, but consider this library as deprecated.
It was implemented because at that time ws library wasn't implementing the WebSocket interface, this is no longer true nowadays, you can simply use ws and skip this wrapper.

I'll add a deprecation warning to the repo and the npm package asap
